#!/bin/bash
#
# ClaudeScope Widget Extension Setup Script
#
# This script helps you set up the Widget Extension in Xcode
# Run this script to see the manual steps needed
#

echo "============================================"
echo "  ClaudeScope Widget Extension Setup Guide"
echo "============================================"
echo ""
echo "The Widget Extension files have been created at:"
echo "  ios/ClaudeScopeWidgetExtension/"
echo ""
echo "To complete the setup, follow these steps in Xcode:"
echo ""
echo "STEP 1: Open Xcode"
echo "  open ios/ClaudeScopeIOS.xcworkspace"
echo ""
echo "STEP 2: Add Widget Extension Target"
echo "  1. File > New > Target..."
echo "  2. Select 'Widget Extension'"
echo "  3. Product Name: ClaudeScopeWidgetExtension"
echo "  4. Check 'Include Configuration App Intent' (optional)"
echo "  5. Click Finish"
echo "  6. When prompted, click 'Activate' to activate the scheme"
echo ""
echo "STEP 3: Replace Generated Files"
echo "  1. Delete the auto-generated .swift file in the new target"
echo "  2. Add our existing files to the target:"
echo "     - ClaudeScopeWidgetExtension/ClaudeScopeWidget.swift"
echo "     - ClaudeScopeWidgetExtension/Info.plist"
echo "     - ClaudeScopeWidgetExtension/Assets.xcassets"
echo "     - ClaudeScopeWidgetExtension/ClaudeScopeWidgetExtension.entitlements"
echo ""
echo "STEP 4: Configure App Groups (CRITICAL)"
echo "  For BOTH targets (ClaudeScopeIOS and ClaudeScopeWidgetExtension):"
echo "  1. Select the target in project settings"
echo "  2. Go to 'Signing & Capabilities'"
echo "  3. Click '+ Capability'"
echo "  4. Add 'App Groups'"
echo "  5. Add group: group.com.claudescope.app"
echo ""
echo "STEP 5: Configure Main App"
echo "  1. Select ClaudeScopeIOS target"
echo "  2. Add ClaudeScopeIOS.entitlements to Build Settings:"
echo "     - Search for 'Code Signing Entitlements'"
echo "     - Set to: ClaudeScopeIOS/ClaudeScopeIOS.entitlements"
echo "  3. Add WidgetDataModule.swift and WidgetDataModule.m to target"
echo "  4. Ensure bridging header is set in Build Settings:"
echo "     - Search for 'Objective-C Bridging Header'"
echo "     - Set to: ClaudeScopeIOS/ClaudeScopeIOS-Bridging-Header.h"
echo ""
echo "STEP 6: Build and Run"
echo "  1. Select the main ClaudeScopeIOS scheme"
echo "  2. Build and run on simulator or device"
echo "  3. Add widget to home screen from the widget gallery"
echo ""
echo "============================================"
echo ""
echo "Opening Xcode workspace now..."
open ios/ClaudeScopeIOS.xcworkspace
